version: "3.9"
services:
  mongodb: 
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - my-net
    
  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks:
      - my-net
    ports:
      - 3000:3000

networks:
  my-net:
    driver: bridge