version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - postgres

  # weather-app:
  #   depends_on:
  #     - postgres
  #   build: .
  #   restart: unless-stopped
  #   env_file: .
  #   command: npm start
  #   ports: 
  #     - "3000:3000"
  #   volumes:
  #     - .:/user/app

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
